/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Base.Conexion;
import java.util.Calendar;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import java.sql.*;

/**
 *
 * @author Oscar Rivera
 */
public class Diagnostico extends javax.swing.JFrame {

    private final Conexion CBD = new Conexion();
    private String sql = "";

    private String TABLA;

    private int ID_INFORME;
//    private int ID_ANTECENDETES;
//    private int ID_LESION;
//    private int ID_MOTIVO_INSATISFACTORIO;
//    private int ID_CANCER;
//    
    private int ID_RESUMEN;
//    private int ID_TEMPORADA;
//    private int ID_SIBASI;
//    private int ID_ESTADO;
//    private int ID_INFORME;
//   private int ID_USUARIO;
//    private int ID_PACIENTE;
//   private int ID_CALENDARIO;

    private int ID_ANTECENDETES;
    private String ANTECENDENTE;

    private int ID_CALENDARIO;
    private int DIA;
    private int MES;
    private int SEMANA;

    private int ID_CAMBIOS;
    private String CAMBIOS;
    private String CAMBIOS_OTROS;

    private int ID_CANCER;
    private String CANCER;

    private int ID_ESTADO;
    private String ESTADO;

    private int ID_LESION;
    private String LESION;

    private int ID_MOTIVO_INSATISFACTORIO;
    private int CELULARIDAD_INADECUADA;
    private int PRESERVACION_INADECUADA;
    private int MATERIAL_EXTRANO;
    private int INFLAMACION;
    private int SANGRE;
    private int CITOLISIS;
    private int AUSENCIA_ZONZ_TRANSFORMACION;
    private int LAMINA_QUEBRADA;
    private int FALTA_INFORMACION_CLINICA;
    private int IDENTIFICACION_INADECUADA;

    private int ID_PACIENTE;
    private int NO_CITOLOGICO;
    private int EXPEDIENTE;
    private int EDAD;
    private String FECHA_TAMIZAJE;

    private int ID_PERMISOS;
    private String PERMISO;

    private int ID_SIBASI;
    private String SIBASI;

    private int ID_COD_SIBASI;
    private String COD_SIBASI;
    private String LUGAR_PROCEDENCIA;

    private int ID_TEMPORADA;
    private String TEMPORADA;

    private int ID_USUARIO;
//    private int ID_PERMISOS;
    private String USUARIO;
    private String PASSWORD;

    ButtonGroup TomaMuestra = new ButtonGroup();
    ButtonGroup Diagnostico = new ButtonGroup();
    ButtonGroup Cambios = new ButtonGroup();
    ButtonGroup Lesion = new ButtonGroup();
    ButtonGroup Cancer = new ButtonGroup();

    /**
     * Creates new form Diagnostico
     */
    public Diagnostico() {
        initComponents();

        TomaMuestra.add(rdo_PrimeraVez);
        TomaMuestra.add(rdo_Vigente);
        TomaMuestra.add(rdo_Atrasado);

        Diagnostico.add(rdo_Satisfactora);
        Diagnostico.add(rdo_NoSatistactoria);

        Cambios.add(rdo_Trinchomonas);
        Cambios.add(rdo_CandidaSP);
        Cambios.add(rdo_TorulopsisSP);
        Cambios.add(rdo_Vaginosis);
        Cambios.add(rdo_Herpex);
        Cambios.add(rdo_Cambios_Otros);

        Lesion.add(rdo_ASCUS);
        Lesion.add(rdo_ASC_H);
        Lesion.add(rdo_HPV);
        Lesion.add(rdo_AG);
        Lesion.add(rdo_BG);
        Lesion.add(rdo_CIS);
        Lesion.add(rdo_BG_HPV);
        Lesion.add(rdo_AG_SI);

        Cancer.add(rdo_CACE);
        Cancer.add(rdo_ADENO);
        Cancer.add(rdo_AGC);
        llenarGUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        rdo_PrimeraVez = new javax.swing.JRadioButton();
        rdo_Vigente = new javax.swing.JRadioButton();
        rdo_Atrasado = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        txt_Edad = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        rdo_Satisfactora = new javax.swing.JRadioButton();
        rdo_NoSatistactoria = new javax.swing.JRadioButton();
        chk_ConCambios = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        rdo_ASCUS = new javax.swing.JRadioButton();
        rdo_HPV = new javax.swing.JRadioButton();
        rdo_BG = new javax.swing.JRadioButton();
        rdo_BG_HPV = new javax.swing.JRadioButton();
        rdo_ASC_H = new javax.swing.JRadioButton();
        rdo_AG = new javax.swing.JRadioButton();
        rdo_CIS = new javax.swing.JRadioButton();
        rdo_AG_SI = new javax.swing.JRadioButton();
        btnGuardar = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        txtCambiosOtros = new javax.swing.JTextField();
        rdo_Trinchomonas = new javax.swing.JRadioButton();
        rdo_CandidaSP = new javax.swing.JRadioButton();
        rdo_TorulopsisSP = new javax.swing.JRadioButton();
        rdo_Vaginosis = new javax.swing.JRadioButton();
        rdo_Herpex = new javax.swing.JRadioButton();
        rdo_Cambios_Otros = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        txt_Expediente = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        rdo_ADENO = new javax.swing.JRadioButton();
        rdo_CACE = new javax.swing.JRadioButton();
        rdo_AGC = new javax.swing.JRadioButton();
        jPanel7 = new javax.swing.JPanel();
        chk_Celularidad = new javax.swing.JCheckBox();
        chk_Fijacion = new javax.swing.JCheckBox();
        chk_Material_Raro = new javax.swing.JCheckBox();
        chk_Inflamacion = new javax.swing.JCheckBox();
        chk_Sangre = new javax.swing.JCheckBox();
        chk_Inadecuada = new javax.swing.JCheckBox();
        chk_Informacion = new javax.swing.JCheckBox();
        chk_Lamina = new javax.swing.JCheckBox();
        chk_Ausencia = new javax.swing.JCheckBox();
        chk_Citolisis = new javax.swing.JCheckBox();
        cmb_Semana = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btn_Informe = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txt_Citologico = new javax.swing.JTextField();
        btn_Salir = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        cmb_Sibasi = new javax.swing.JComboBox<>();
        cmb_CodigoSibasi = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(7, 2147483647));
        setResizable(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Antecedentes de Tamizaje"));

        rdo_PrimeraVez.setText("Primera Vez");

        rdo_Vigente.setText("Vigente");

        rdo_Atrasado.setText("Atrasado");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdo_PrimeraVez)
                    .addComponent(rdo_Vigente)
                    .addComponent(rdo_Atrasado))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rdo_PrimeraVez)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdo_Vigente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdo_Atrasado)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setText("Edad");

        txt_Edad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_EdadActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Negativa"));

        rdo_Satisfactora.setText("SPE");
        rdo_Satisfactora.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rdo_SatisfactoraStateChanged(evt);
            }
        });

        rdo_NoSatistactoria.setText("NSPE");
        rdo_NoSatistactoria.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rdo_NoSatistactoriaStateChanged(evt);
            }
        });

        chk_ConCambios.setText("CCAABI");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdo_Satisfactora)
                    .addComponent(rdo_NoSatistactoria)
                    .addComponent(chk_ConCambios))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rdo_Satisfactora)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdo_NoSatistactoria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chk_ConCambios)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Lesion"));

        rdo_ASCUS.setText("ASCUS");

        rdo_HPV.setText("HPV");

        rdo_BG.setText("BG");

        rdo_BG_HPV.setText("BG+HPV");

        rdo_ASC_H.setText("ASC H");

        rdo_AG.setText("AG");

        rdo_CIS.setText("CIS");

        rdo_AG_SI.setText("AG+SI");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdo_ASCUS)
                    .addComponent(rdo_HPV)
                    .addComponent(rdo_BG)
                    .addComponent(rdo_BG_HPV))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdo_AG_SI)
                    .addComponent(rdo_CIS)
                    .addComponent(rdo_AG)
                    .addComponent(rdo_ASC_H))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdo_ASCUS)
                    .addComponent(rdo_ASC_H))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdo_HPV)
                    .addComponent(rdo_AG))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdo_BG)
                    .addComponent(rdo_CIS))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdo_BG_HPV)
                    .addComponent(rdo_AG_SI)))
        );

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("MicroOrganismos/Cambios"));

        rdo_Trinchomonas.setText("Trinchomonas Vaginales");

        rdo_CandidaSP.setText("Micoticos Consistentes con Candida SP");

        rdo_TorulopsisSP.setText("Micoticos Consistentes con Torulopsis SP");

        rdo_Vaginosis.setText("Camb. en la Flora Suges. de Vaginosis Bacteriana");

        rdo_Herpex.setText("Camb. Celulares Asociados a Herpes Simplex");

        rdo_Cambios_Otros.setText("Otros");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(rdo_Cambios_Otros)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCambiosOtros, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(rdo_CandidaSP)
                    .addComponent(rdo_Trinchomonas)
                    .addComponent(rdo_TorulopsisSP)
                    .addComponent(rdo_Vaginosis)
                    .addComponent(rdo_Herpex)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rdo_Trinchomonas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdo_CandidaSP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdo_TorulopsisSP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdo_Vaginosis)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdo_Herpex)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdo_Cambios_Otros)
                    .addComponent(txtCambiosOtros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jLabel3.setText("No Citologio");

        txt_Expediente.setEnabled(false);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Cancer"));

        rdo_ADENO.setText("ADENO");

        rdo_CACE.setText("CACE");

        rdo_AGC.setText("AGC");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdo_ADENO)
                    .addComponent(rdo_AGC)
                    .addComponent(rdo_CACE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(rdo_CACE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdo_ADENO)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rdo_AGC)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Motivo Insatisfactorio"));

        chk_Celularidad.setText("Celularidad inadecuada");

        chk_Fijacion.setText("Fijacion/Preservacion inadecuada");

        chk_Material_Raro.setText("Material Extrano");

        chk_Inflamacion.setText("Inflamacion");

        chk_Sangre.setText("Sangre");

        chk_Inadecuada.setText("Identificacion inadecuada");

        chk_Informacion.setText("Falta Informacion Clinica");

        chk_Lamina.setText("Lamina Quebrada");

        chk_Ausencia.setText("Ausencia zona de transformacion");

        chk_Citolisis.setText("Citolisi");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chk_Celularidad)
                    .addComponent(chk_Fijacion)
                    .addComponent(chk_Material_Raro)
                    .addComponent(chk_Inflamacion)
                    .addComponent(chk_Sangre)
                    .addComponent(chk_Citolisis)
                    .addComponent(chk_Ausencia)
                    .addComponent(chk_Lamina)
                    .addComponent(chk_Informacion)
                    .addComponent(chk_Inadecuada))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chk_Celularidad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chk_Fijacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chk_Material_Raro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chk_Inflamacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chk_Sangre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chk_Citolisis)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chk_Ausencia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chk_Lamina)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chk_Informacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chk_Inadecuada)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cmb_Semana.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1er Semana", "2da Semana", "3ra Semana", "4ra Semana", "5ta Semana" }));

        jLabel4.setText("2017");

        jLabel5.setText("Mes");

        jLabel6.setText("Positiva,Negativa o Insatisfactoria");

        btn_Informe.setText("Informe");

        jLabel7.setText("Expediente");

        txt_Citologico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_CitologicoActionPerformed(evt);
            }
        });

        btn_Salir.setText("Salir");

        jLabel8.setText("Codigo");

        cmb_Sibasi.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_SibasiItemStateChanged(evt);
            }
        });

        cmb_CodigoSibasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_CodigoSibasiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btn_Informe)
                                    .addComponent(btnGuardar))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(20, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_Edad, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_Citologico, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_Expediente, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmb_Semana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(jLabel8)
                        .addGap(10, 10, 10)
                        .addComponent(cmb_Sibasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmb_CodigoSibasi, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_Edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txt_Expediente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_Citologico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(cmb_Sibasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmb_Semana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmb_CodigoSibasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Informe, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LimpiarGUI() {
        //Antecendestes
        this.rdo_PrimeraVez.setSelected(false);
        this.rdo_Vigente.setSelected(false);
        this.rdo_Atrasado.setSelected(false);
        TomaMuestra.clearSelection();
        //Estado
        Diagnostico.clearSelection();
        this.rdo_Satisfactora.setSelected(false);
        this.rdo_NoSatistactoria.setSelected(false);
        this.chk_ConCambios.setSelected(false);
        //Cambios
        Cambios.clearSelection();
        this.rdo_Trinchomonas.setSelected(false);
        this.rdo_CandidaSP.setSelected(false);
        this.rdo_TorulopsisSP.setSelected(false);
        this.rdo_Vaginosis.setSelected(false);
        this.rdo_Herpex.setSelected(false);
        this.rdo_Cambios_Otros.setSelected(false);
        this.txtCambiosOtros.setText("");
        this.txtCambiosOtros.setEnabled(false);
        //Motivo Insatisfactorio
        this.chk_Celularidad.setSelected(false);
        this.chk_Fijacion.setSelected(false);
        this.chk_Material_Raro.setSelected(false);
        this.chk_Inflamacion.setSelected(false);
        this.chk_Sangre.setSelected(false);
        this.chk_Citolisis.setSelected(false);
        this.chk_Ausencia.setSelected(false);
        this.chk_Lamina.setSelected(false);
        this.chk_Informacion.setSelected(false);
        this.chk_Inadecuada.setSelected(false);
        //Lesion
        Lesion.clearSelection();
        this.rdo_ASCUS.setSelected(false);
        this.rdo_HPV.setSelected(false);
        this.rdo_BG.setSelected(false);
        this.rdo_BG_HPV.setSelected(false);
        this.rdo_ASC_H.setSelected(false);
        this.rdo_AG.setSelected(false);
        this.rdo_CIS.setSelected(false);
        this.rdo_AG_SI.setSelected(false);
        //Cancer
        Cancer.clearSelection();
        this.rdo_CACE.setSelected(false);
        this.rdo_ADENO.setSelected(false);
        this.rdo_AGC.setSelected(false);
        //Informacion
        this.txt_Edad.setText("");
        this.txt_Citologico.setText("");
        this.txt_Expediente.setText("");
        this.txt_Expediente.setEnabled(false);
    }

    private void LimpiarVariables() {

    }

    private void obtenerDatosGUI() {
        //Antecedentes
        if (this.rdo_PrimeraVez.isSelected() == true) {
            ANTECENDENTE = "Primera Vez";//1
        }
        if (this.rdo_Vigente.isSelected() == true) {
            ANTECENDENTE = "Vigente";//2
        }
        if (this.rdo_Atrasado.isSelected() == true) {
            ANTECENDENTE = "Atrasado";//3
        }
        //Estado
        if (this.rdo_Satisfactora.isSelected() == true) {
            ESTADO = "Positiva";//1
            if (this.chk_ConCambios.isSelected() == true) {
                ESTADO = "Negativa";//2
            }
        }
        if (this.rdo_NoSatistactoria.isSelected() == true) {
            ESTADO = "No Satisfactoria";//3
        }

        //Cambios
        if (this.rdo_Trinchomonas.isSelected() == true) {
            CAMBIOS = "Trinchomonas";//1
        }
        if (this.rdo_CandidaSP.isSelected() == true) {
            CAMBIOS = "CandidaSP";//2
        }
        if (this.rdo_TorulopsisSP.isSelected() == true) {
            CAMBIOS = "TorulopsisSP";//3
        }
        if (this.rdo_Vaginosis.isSelected() == true) {
            CAMBIOS = "Vaginosis";//4
        }
        if (this.rdo_Herpex.isSelected() == true) {
            CAMBIOS = "Herpex";//5
        }
        if (this.rdo_Cambios_Otros.isSelected() == true) {
            CAMBIOS = txtCambiosOtros.getText();//6
        }
        //Motivo Insatisfactorio
        if (this.chk_Celularidad.isSelected() == true) {
            CELULARIDAD_INADECUADA = 1;
        }
        if (this.chk_Fijacion.isSelected() == true) {
            PRESERVACION_INADECUADA = 1;
        }
        if (this.chk_Material_Raro.isSelected() == true) {
            MATERIAL_EXTRANO = 1;
        }
        if (this.chk_Inflamacion.isSelected() == true) {
            INFLAMACION = 1;
        }
        if (this.chk_Sangre.isSelected() == true) {
            SANGRE = 1;
        }
        if (this.chk_Citolisis.isSelected() == true) {
            CITOLISIS = 1;
        }
        if (this.chk_Ausencia.isSelected() == true) {
            AUSENCIA_ZONZ_TRANSFORMACION = 1;
        }
        if (this.chk_Lamina.isSelected() == true) {
            LAMINA_QUEBRADA = 1;
        }
        if (this.chk_Informacion.isSelected() == true) {
            FALTA_INFORMACION_CLINICA = 1;
        }
        if (this.chk_Inadecuada.isSelected() == true) {
            IDENTIFICACION_INADECUADA = 1;
        }
        //Lesion
        if (this.rdo_ASCUS.isSelected() == true) {
            LESION = "ASCUS";//1
        }
        if (this.rdo_HPV.isSelected() == true) {
            LESION = "HPV";//2
        }
        if (this.rdo_BG.isSelected() == true) {
            LESION = "BG";//3
        }
        if (this.rdo_BG_HPV.isSelected() == true) {
            LESION = "BG+HPV";//4
        }
        if (this.rdo_ASC_H.isSelected() == true) {
            LESION = "ADC H";//5
        }
        if (this.rdo_AG.isSelected() == true) {
            LESION = "AG";//6
        }
        if (this.rdo_CIS.isSelected() == true) {
            LESION = "CIS";//7
        }
        if (this.rdo_AG_SI.isSelected() == true) {
            LESION = "AG+SI";//8
        }
        //Cancer
        if (rdo_CACE.isSelected() == true) {
            CANCER = "CACE";//1
        }
        if (rdo_ADENO.isSelected() == true) {
            CANCER = "ADENO";//2
        }
        if (rdo_AGC.isSelected() == true) {
            CANCER = "AGC";//3
        }
        //Informacion
        EDAD = Integer.parseInt(txt_Edad.getText());
        NO_CITOLOGICO = Integer.parseInt(txt_Citologico.getText());
        EXPEDIENTE = Integer.parseInt(txt_Expediente.getText());
        SEMANA = cmb_Semana.getSelectedIndex();
        Calendar now = Calendar.getInstance();
        MES = now.get(Calendar.MONTH);
        DIA = now.get(Calendar.DAY_OF_MONTH);
        COD_SIBASI = cmb_CodigoSibasi.getSelectedItem().toString();
        SIBASI = cmb_Sibasi.getSelectedItem().toString();
        //COdigo, Mes y Semana

    }

    private void llenarGUI() {
        // SELECT `ID_SIBASI`, `SIBASI` FROM `sibasis` WHERE 1

        //SELECT `ID_COD_SIBASI`, `ID_SIBASI`, `CODIGO`, `LUGAR_PROCEDENCIA` FROM `cod_sibasi` WHERE 1
        try {

            if (CBD.conectar()) {
                sql = "SELECT `ID_SIBASI`, `SIBASI` FROM `sibasis` ";
                Statement stmt = null;
                ResultSet rs = CBD.Seleccionar(sql);
                
                while (rs.next()) {
                    cmb_Sibasi.addItem(String.valueOf(rs.getString("SIBASI")));
                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

    }

    private void GuardarDatos() {
        
        
        
//INSERT INTO `motivo_insatisfactorio`(`ID_MOTIVO_INSATISFACTORIO`, `CELULARIDAD_INADECUADA`, `PRESERVACION_INADECUADA`, `MATERIAL_EXTRANO`, `INFLAMACION`, `CITOLISIS`, `AUSENCIA_ZONZ_TRANSFORMACION`, `LAMINA_QUEBRADA`, `FALTA_INFORMACION_CLINICA`, `IDENTIFICACION_INADECUADA`, `SANGRE`) VALUES ([value-1],[value-2],[value-3],[value-4],[value-5],[value-6],[value-7],[value-8],[value-9],[value-10],[value-11])

//SELECT * FROM `lesion` WHERE (( `LESION` = 0))

//SELECT `antecedentes`.`ID_ANTECENDETES` FROM  `antecedentes` WHERE (( `ANTECENDENTE` =0))

//SELECT `cancer`.`ID_CANCER`FROM `cancer`WHERE (( `CANCER` =0))

//SELECT `ID_CAMBIOS`, `CAMBIOS`, `CAMBIOS_OTROS` FROM `cambios` WHERE 1

// SELECT `ID_SIBASI`, `SIBASI` FROM `sibasis` WHERE 1

//SELECT `ID_COD_SIBASI`, `ID_SIBASI`, `CODIGO`, `LUGAR_PROCEDENCIA` FROM `cod_sibasi` WHERE 1

//SELECT `ID_ESTADO`, `ESTADO` FROM `estado` WHERE 1

//SELECT `ID_TEMPORADA`, `TEMPORADA` FROM `temporada` WHERE 1

//INSERT INTO `paciente`( `NO_CITOLOGICO`, `EXPEDIENTE`, `EDAD`, `FECHA_TAMIZAJE`) VALUES ([value-1],[value-2],[value-3],[value-4])

//INSERT INTO `resumen`( `ID_TEMPORADA`, `ID_SIBASI`, `ID_ESTADO`, `ID_INFORME`, `ID_USUARIO`, `ID_PACIENTE`, `ID_CALENDARIO`) VALUES ([value-1],[value-2],[value-3],[value-4],[value-5],[value-6],[value-7])
   
//INSERT INTO `informe`(`ID_INFORME`, `ID_ANTECENDETES`, `ID_LESION`, `ID_MOTIVO_INSATISFACTORIO`, `ID_CANCER`, `ID_CAMBIOS`) VALUES ([value-1],[value-2],[value-3],[value-4],[value-5],[value-6])
     
    }

    private void txt_EdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_EdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_EdadActionPerformed

    private void rdo_SatisfactoraStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rdo_SatisfactoraStateChanged
        if (rdo_Satisfactora.isSelected() == true) {
            txt_Expediente.setEnabled(true);
        }

    }//GEN-LAST:event_rdo_SatisfactoraStateChanged

    private void rdo_NoSatistactoriaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rdo_NoSatistactoriaStateChanged
        if (rdo_NoSatistactoria.isSelected() == true) {
            txt_Expediente.setEnabled(false);
        }
    }//GEN-LAST:event_rdo_NoSatistactoriaStateChanged

    private void txt_CitologicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_CitologicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_CitologicoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        LimpiarGUI();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void cmb_SibasiItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_SibasiItemStateChanged
        // TODO add your handling code here:
        try {

            if (CBD.conectar()) {
                cmb_CodigoSibasi.removeAllItems();
                ID_SIBASI = cmb_Sibasi.getSelectedIndex() + 1;
                sql = "SELECT `ID_COD_SIBASI`, `ID_SIBASI`, `CODIGO`, `LUGAR_PROCEDENCIA` FROM `cod_sibasi` WHERE ID_SIBASI= " + ID_SIBASI + "";
                Statement stmt = null;
                ResultSet rs = CBD.Seleccionar(sql);
                
                while (rs.next()) {
                    
                    cmb_CodigoSibasi.addItem(String.valueOf(rs.getString("CODIGO")+" - " + String.valueOf(rs.getString("LUGAR_PROCEDENCIA"))));
                }
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_cmb_SibasiItemStateChanged

    private void cmb_CodigoSibasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_CodigoSibasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_CodigoSibasiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Diagnostico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Diagnostico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Diagnostico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Diagnostico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Diagnostico().setVisible(true);
                

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btn_Informe;
    private javax.swing.JButton btn_Salir;
    private javax.swing.JCheckBox chk_Ausencia;
    private javax.swing.JCheckBox chk_Celularidad;
    private javax.swing.JCheckBox chk_Citolisis;
    private javax.swing.JCheckBox chk_ConCambios;
    private javax.swing.JCheckBox chk_Fijacion;
    private javax.swing.JCheckBox chk_Inadecuada;
    private javax.swing.JCheckBox chk_Inflamacion;
    private javax.swing.JCheckBox chk_Informacion;
    private javax.swing.JCheckBox chk_Lamina;
    private javax.swing.JCheckBox chk_Material_Raro;
    private javax.swing.JCheckBox chk_Sangre;
    private javax.swing.JComboBox<String> cmb_CodigoSibasi;
    private javax.swing.JComboBox<String> cmb_Semana;
    private javax.swing.JComboBox<String> cmb_Sibasi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JRadioButton rdo_ADENO;
    private javax.swing.JRadioButton rdo_AG;
    private javax.swing.JRadioButton rdo_AGC;
    private javax.swing.JRadioButton rdo_AG_SI;
    private javax.swing.JRadioButton rdo_ASCUS;
    private javax.swing.JRadioButton rdo_ASC_H;
    private javax.swing.JRadioButton rdo_Atrasado;
    private javax.swing.JRadioButton rdo_BG;
    private javax.swing.JRadioButton rdo_BG_HPV;
    private javax.swing.JRadioButton rdo_CACE;
    private javax.swing.JRadioButton rdo_CIS;
    private javax.swing.JRadioButton rdo_Cambios_Otros;
    private javax.swing.JRadioButton rdo_CandidaSP;
    private javax.swing.JRadioButton rdo_HPV;
    private javax.swing.JRadioButton rdo_Herpex;
    private javax.swing.JRadioButton rdo_NoSatistactoria;
    private javax.swing.JRadioButton rdo_PrimeraVez;
    private javax.swing.JRadioButton rdo_Satisfactora;
    private javax.swing.JRadioButton rdo_TorulopsisSP;
    private javax.swing.JRadioButton rdo_Trinchomonas;
    private javax.swing.JRadioButton rdo_Vaginosis;
    private javax.swing.JRadioButton rdo_Vigente;
    private javax.swing.JTextField txtCambiosOtros;
    private javax.swing.JTextField txt_Citologico;
    private javax.swing.JTextField txt_Edad;
    private javax.swing.JTextField txt_Expediente;
    // End of variables declaration//GEN-END:variables
}
